
export const gradeScales = {
  VC: [
    { grade: "VB", color: "border-gray-500" },
    { grade: "V0", color: "border-gray-500" },
    { grade: "V1", color: "border-yellow-500" },
    { grade: "V2", color: "border-yellow-500" },
    { grade: "V3", color: "border-orange-500" },
    { grade: "V4", color: "border-orange-500" },
    { grade: "V5", color: "border-green-500" },
    { grade: "V6", color: "border-green-500" },
    { grade: "V7", color: "border-blue-500" },
    { grade: "V8", color: "border-blue-500" },
    { grade: "V9", color: "border-red-500" },
    { grade: "V10", color: "border-red-500" },
    { grade: "V11", color: "border-zinc-950" },
    { grade: "V12", color: "border-zinc-950" },
    { grade: "V13", color: "border-zinc-300" },
    { grade: "V14", color: "border-zinc-300" },
  ],
  VS: [
    { grade: "VB", color: "border-gray-500" },
    { grade: "V0", color: "border-gray-500" },
    { grade: "V1", color: "border-yellow-500" },
    { grade: "V2", color: "border-yellow-500" },
    { grade: "V3", color: "border-green-500" },
    { grade: "V4", color: "border-green-500" },
    { grade: "V5", color: "border-blue-500" },
    { grade: "V6", color: "border-blue-500" },
    { grade: "V7", color: "border-red-500" },
    { grade: "V8", color: "border-red-500" },
    { grade: "V9", color: "border-purple-500" },
    { grade: "V10", color: "border-purple-500" },
    { grade: "V11", color: "border-zinc-950" },
    { grade: "V12", color: "border-zinc-950" },
    { grade: "V13", color: "border-zinc-300" },
    { grade: "V14", color: "border-zinc-300" },
  ],
  FT: [
    { grade: "4", color: "border-yellow-500" },
    { grade: "5", color: "border-green-500" },
    { grade: "6A", color: "border-blue-500" },
    { grade: "6B", color: "border-blue-500" },
    { grade: "6C", color: "border-red-500" },
    { grade: "7A", color: "border-red-500" },
    { grade: "7B", color: "border-purple-500" },
    { grade: "7C", color: "border-purple-500" },
    { grade: "8A", color: "border-zinc-950" },
    { grade: "8B", color: "border-zinc-950" },
    { grade: "8C", color: "border-zinc-300" },
    { grade: "9A", color: "border-zinc-300" },
  ],
  OVS: [
    { grade: "VB", color: "border-gray-500" },
    { grade: "V0", color: "border-gray-500" },
    { grade: "V1", color: "border-yellow-500" },
    { grade: "V2", color: "border-yellow-500" },
    { grade: "V3", color: "border-green-500" },
    { grade: "V4", color: "border-green-500" },
    { grade: "V5", color: "border-blue-500" },
    { grade: "V6", color: "border-blue-500" },
    { grade: "V7", color: "border-red-500" },
    { grade: "V8", color: "border-red-500" },
    { grade: "V9", color: "border-purple-500" },
    { grade: "V10", color: "border-purple-500" },
    { grade: "V11", color: "border-zinc-950" },
    { grade: "V12", color: "border-zinc-950" },
    { grade: "V13", color: "border-zinc-300" },
    { grade: "V14", color: "border-zinc-300" },
  ],
  OFT: [
    { grade: "4", color: "border-yellow-500" },
    { grade: "5", color: "border-green-500" },
    { grade: "6A", color: "border-blue-500" },
    { grade: "6B", color: "border-blue-500" },
    { grade: "6C", color: "border-red-500" },
    { grade: "7A", color: "border-red-500" },
    { grade: "7B", color: "border-purple-500" },
    { grade: "7C", color: "border-purple-500" },
    { grade: "8A", color: "border-zinc-950" },
    { grade: "8B", color: "border-zinc-950" },
    { grade: "8C", color: "border-zinc-300" },
    { grade: "9A", color: "border-zinc-300" },
  ],
  MG: [
    { grade: "3", color: "border-yellow-500" },
    { grade: "4", color: "border-green-500" },
    { grade: "5", color: "border-blue-500" },
    { grade: "6", color: "border-red-500" },
    { grade: "7", color: "border-purple-500" },
    { grade: "8", color: "border-zinc-950" },
    { grade: "9", color: "border-zinc-300" },
  ],
};
